import Head from "next/head";
import NavigationComp from "./NavigationComp";
import FooterComp from "./FooterComp";

const LayoutComp: React.FC<any> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Test - Titel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationComp />
      {children}
      <FooterComp />
    </div>
  );
};

export default LayoutComp;
